import tkinter as tk
from tkinter import *
from tkinter import ttk
window = tk.Tk()
window.title("                                                           T-Town Veterinary Clinic Database")
dogphoto = PhotoImage(file="dog.png")
SearchbyName = tk.Button(window,text="Search by Name")
SBNentry = tk.Entry(window,text="")
Labeldogphoto = tk.Label(window,image=dogphoto, borderwidth=3)
Cdata = tk.Label(window, text="Client Database")
lName = tk.Label(window,text="Name")
eName = tk.Entry(window)
lType = tk.Label(window,text="Type")
eType = tk.Entry(window)
lBreed = tk.Label(window,text="Breed")
eBreed = tk.Entry(window)
lOwner = tk.Label(window,text="Owner")
eOwner = tk.Entry(window)
lBirthdate = tk.Label(window,text="Birthdate")
eBirthdate = tk.Entry(window)
bSaveEntry = tk.Button(window,text="Save Entry")
bPrevious = tk.Button(window,text="< Previous")
bNext = tk.Button(window,text="Next >")

Labeldogphoto.grid(row = 0, column = 0, rowspan = 3)
SearchbyName.grid(row = 0, column = 3)
SBNentry.grid(row = 0, column =4)
Cdata.grid(row = 1, column = 2)
lName.grid(row = 4, column = 0)
eName.grid(row = 5, column = 0)
lType.grid(row = 4, column = 1)
eType.grid(row = 5, column = 1)
lBreed.grid(row = 4, column = 2)
eBreed.grid(row = 5, column = 2)
lOwner.grid(row = 4, column = 3)
eOwner.grid(row = 5, column = 3)
lBirthdate.grid(row = 4, column = 4)
eBirthdate.grid(row = 5, column = 4)
bPrevious.grid(row = 6, column = 0)
bSaveEntry.grid(row = 6, column = 2)
bNext.grid(row = 6, column = 4)

window.mainloop()